# syntax for this file https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# help on github actions: https://docs.github.com/en/actions/learn-github-actions/introduction-to-github-actions
name: BuildFirmware

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  #push:
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  buildfirmware:
    runs-on: ubuntu-latest
    container:
      image: deroyal/msp430
    steps:
      - uses: actions/checkout@v2
      - name: Create Eclipse/CCS Workspace
        run: ls -al /
      - name: Trigger release build
        run: ls -al ~
      - name: t
        run: ls -al
      - name: u
        run: ls -al /__w/jubilant-potato/jubilant-potato
      - name: Archive Results
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: ./ProsperaFlex/Source/Release/
          
